# RISC-V: RV64D

name: rv64d

instructions:
  - mnemonic: fcvtld
    length: 32
    format: R
    key:
      opcode: 83
      rs2: 2
      funct7: 97
  - mnemonic: fcvtlud
    length: 32
    format: R
    key:
      opcode: 83
      rs2: 3
      funct7: 97
  - mnemonic: fmvxd
    length: 32
    format: R
    key:
      opcode: 83
      rs2: 0
      funct7: 113
  - mnemonic: fcvtdl
    length: 32
    format: R
    key:
      opcode: 83
      rs2: 2
      funct7: 105
  - mnemonic: fcvtslu
    length: 32
    format: R
    key:
      opcode: 83
      rs2: 3
      funct7: 105
  - mnemonic: fmvdx
    length: 32
    format: R
    key:
      opcode: 83
      rs2: 0
      funct7: 121
