# Test Base Extension w/ dependencies

name: with-deps-complex
extends:
  - base1-complex
  - base2-complex

endianness: little
word-size: 32
byte-size: 8

units:
  - name: cpu
    registers:
    - name: r0
      id: 0
      size: 32
      constituents:
        - id: 1
          enclosing-index: 1
        - id: 2
          enclosing-index: 2
      alias: zero
    - name: r1
      id: 1
      size: 16
      type: float
      enclosing: 0
      constant: 3.14
      aliases: [foo, bar]
instructions:
  - mnemonic: add
    length: 69
    format: R
    key:
      opcode: 6
      function: 3
  - mnemonic: sub
    length: 69
    format: R
    key:
      opcode: 9
      function: 3
