# RISC-V: RV32M

name: rv32m

instructions:
  - mnemonic: mul
    length: 32
    format: R
    key:
      opcode: 51
      funct3: 0
      funct7: 1
  - mnemonic: mulh
    length: 32
    format: R
    key:
      opcode: 51
      funct3: 1
      funct7: 1
  - mnemonic: mulhsu
    length: 32
    format: R
    key:
      opcode: 51
      funct3: 2
      funct7: 1
  - mnemonic: mulhu
    length: 32
    format: R
    key:
      opcode: 51
      funct3: 3
      funct7: 1
  - mnemonic: div
    length: 32
    format: R
    key:
      opcode: 51
      funct3: 4
      funct7: 1
  - mnemonic: divu
    length: 32
    format: R
    key:
      opcode: 51
      funct3: 5
      funct7: 1
  - mnemonic: rem
    length: 32
    format: R
    key:
      opcode: 51
      funct3: 6
      funct7: 1
  - mnemonic: remu
    length: 32
    format: R
    key:
      opcode: 51
      funct3: 7
      funct7: 1
