# RISC-V: RV64I

name: rv64i

extends: rv32i

word-size: 64
byte-size: 8
reset-units: true

instructions:
  - mnemonic: lwu
    length: 32
    format: I
    key:
      opcode: 3
      funct3: 6
  - mnemonic: ld
    length: 32
    format: I
    key:
      opcode: 3
      funct3: 3
  - mnemonic: sd
    length: 32
    format: S
    key:
      opcode: 35
      funct3: 1
      funct7: 0
  - mnemonic: slli
    length: 32
    format: R
    key:
      opcode: 19
      funct3: 1
      funct7: 0
  - mnemonic: srai
    length: 32
    format: R
    key:
      opcode: 19
      funct3: 5
      funct7: 1
  - mnemonic: addiw
    length: 32
    format: I
    key:
      opcode: 27
      funct3: 0
  - mnemonic: slliw
    length: 32
    format: R
    key:
      opcode: 27
      funct3: 1
      funct7: 0
  - mnemonic: srliw
    length: 32
    format: R
    key:
      opcode: 27
      funct3: 5
      funct7: 0
  - mnemonic: sraiw
    length: 32
    format: R
    key:
      opcode: 27
      funct3: 5
      funct7: 32
  - mnemonic: addw
    length: 32
    format: R
    key:
      opcode: 59
      funct3: 0
      funct7: 0
  - mnemonic: subw
    length: 32
    format: R
    key:
      opcode: 59
      funct3: 0
      funct7: 32
  - mnemonic: sllw
    length: 32
    format: R
    key:
      opcode: 59
      funct3: 1
      funct7: 0
  - mnemonic: srlw
    length: 32
    format: R
    key:
      opcode: 59
      funct3: 5
      funct7: 0
  - mnemonic: sraw
    length: 32
    format: R
    key:
      opcode: 59
      funct3: 5
      funct7: 32
units:
  - name: cpu
    registers:
      - name: x0
        id: 0
        alias: zero
        size: 64
        constant: 0
      - name: x1
        id: 1
        size: 64
      - name: x2
        id: 2
        size: 64
      - name: x3
        id: 3
        size: 64
      - name: x4
        id: 4
        size: 64
      - name: x5
        id: 5
        size: 64
      - name: x6
        id: 6
        size: 64
      - name: x7
        id: 7
        size: 64
      - name: x8
        id: 8
        size: 64
      - name: x9
        id: 9
        size: 64
      - name: x10
        id: 10
        size: 64
      - name: x11
        id: 11
        size: 64
      - name: x12
        id: 12
        size: 64
      - name: x13
        id: 13
        size: 64
      - name: x14
        id: 14
        size: 64
      - name: x15
        id: 15
        size: 64
      - name: x16
        id: 16
        size: 64
      - name: x17
        id: 17
        size: 64
      - name: x18
        id: 18
        size: 64
      - name: x19
        id: 19
        size: 64
      - name: x20
        id: 20
        size: 64
      - name: x21
        id: 21
        size: 64
      - name: x22
        id: 22
        size: 64
      - name: x23
        id: 23
        size: 64
      - name: x24
        id: 24
        size: 64
      - name: x25
        id: 25
        size: 64
      - name: x26
        id: 26
        size: 64
      - name: x27
        id: 27
        size: 64
      - name: x28
        id: 28
        size: 64
      - name: x29
        id: 29
        size: 64
      - name: x30
        id: 30
        size: 64
      - name: x31
        id: 31
        size: 64
      - name: pc
        id: 32
        size: 64
        type: program-counter
